# Generated by Django 4.2.6 on 2023-10-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_alter_post_options_remove_post_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeed",
            name="read_posts",
            field=models.ManyToManyField(
                blank=True, help_text="Posts that read by the user", related_name="read_posts", to="feed.post"
            ),
        ),
    ]
